services:
  mongodb:
    image: mongo:6.0
    container_name: solar-system-mongodb
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - solar-system-network

networks:
  solar-system-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local